### ISSUE TITLE
Why require iOS 9?

### ISSUE THREAD

**Issue by ndrewh** [henrinormak/Heimdall#22]
In cde15b3393ab612987ab466ec741da7aea3780db the Podspec was edited to specify the platform as iOS 9.0. Apparently this means that the host project's "Minimum Deployment Target" must be iOS 9 or greater, or else `pod install` fails with:

```
[!] Unable to satisfy the following requirements:

- `Heimdall (~> 0.2.0)` required by `Podfile`

Specs satisfying the `Heimdall (~> 0.2.0)` dependency were found, but they required a higher minimum deployment target.
```

As far as I know, apps written in Swift 2.0 (with Xcode 7) can support older versions of iOS, such as iOS 8, and as far as I can tell, there were no changes made to this framework to make it specifically incompatible with iOS 8.

If this framework still supports iOS 8, I think this should be changed back.

**Comment by henrinormak** [comment]
This is now fixed, thanks for notifying! :+1:

**Comment by alinandrews** [comment]
I still have this issue. I am running on cocoapods 0.39 version
My minimum deployment target is 8.0 and I run script
"source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Socket.IO-Client-Swift', '~> 3.1.4' # Or latest version"

I get the same issue as above user.

[!] Unable to satisfy the following requirements:
- `Socket.IO-Client-Swift (~> 3.1.4)` required by `Podfile`
  Specs satisfying the `Socket.IO-Client-Swift (~> 3.1.4)` dependency were found, but they required a higher minimum deployment target.

**Comment by henrinormak** [comment]
I don't understand why this is here? This is not the Socket.IO repository, I think you may want to file an issue with [these folks](https://github.com/socketio/socket.io-client-swift) directly

**Comment by alinandrews** [comment]
I am sorry. Wrong place. Thanks for the help
